apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: amd-gpu-helm
  namespace: kube-system
spec:
  interval: 10m0s
  url: https://rocm.github.io/k8s-device-plugin
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: amd-gpu
  namespace: kube-system
spec:
  chart:
    spec:
      chart: amd-gpu
      sourceRef:
        kind: HelmRepository
        name: amd-gpu-helm
  interval: 10m0s
---
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Provider
metadata:
  name: flux-email-notifier
  namespace: kube-system
spec:
  type: generic
  address: http://flux-email-notifier-svc.flux-system:3000
---
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Alert
metadata:
  name: amd-gpu-flux-errors
  namespace: kube-system
spec:
  providerRef:
    name: flux-email-notifier
  eventSeverity: error
  eventSources:
    - kind: HelmRepository
      name: amd-gpu-helm
    - kind: HelmRelease
      name: amd-gpu
