apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: amd-gpu-helm
  namespace: kube-system
spec:
  interval: 10m0s
  url: https://radeonopencompute.github.io/k8s-device-plugin
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: amd-gpu
  namespace: kube-system
spec:
  chart:
    spec:
      chart: amd-gpu
      sourceRef:
        kind: HelmRepository
        name: amd-gpu-helm
  interval: 10m0s
