---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets
  namespace: unifi-parental-controls
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: unifi-access-creds
  namespace: unifi-parental-controls
spec:
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  refreshInterval: 1h
  target:
    name: unifi-access-creds
  dataFrom:
    - extract:
        key: unifi-access-creds
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: unifi-parental-controls-api
  namespace: unifi-parental-controls
  labels:
    app: unifi-parental-controls-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: unifi-parental-controls-api
  template:
    metadata:
      labels:
        app: unifi-parental-controls-api
    spec:
      containers:
      - image: ghcr.io/rparmer/unifi-parental-controls-api:latest
        imagePullPolicy: Always
        name: api
        env:
        - name: UNIFI_INSECURE
          value: 'true'
        - name: UNIFI_USERNAME
          valueFrom:
            secretKeyRef:
              name: unifi-access-creds
              key: username
        - name: UNIFI_PASSWORD
          valueFrom:
            secretKeyRef:
              name: unifi-access-creds
              key: password
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: unifi-parental-controls-ui
  namespace: unifi-parental-controls
  labels:
    app: unifi-parental-controls-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: unifi-parental-controls-ui
  template:
    metadata:
      labels:
        app: unifi-parental-controls-ui
    spec:
      containers:
      - image: ghcr.io/rparmer/unifi-parental-controls-ui:latest
        imagePullPolicy: Always
        name: ui
        env:
        - name: UNIFI_PARENTAL_CONTROLS_API
          value: https://api.unificontrols.internal.russparmer.dev
        ports:
        - containerPort: 3000
          name: http
          protocol: TCP
