apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: prometheus-community
  namespace: monitoring
spec:
  interval: 10m0s
  url: https://prometheus-community.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  chart:
    spec:
      chart: kube-prometheus-stack
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
  interval: 10m0s
  values:
    grafana:
      enabled: false
    prometheus:
      ingress:
        enabled: enabled
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt
        tls:
          - secretName: prometheus-tls
            hosts:
              - prometheus.internal.russparmer.dev
        hosts:
          - prometheus.internal.russparmer.dev
        path: /
        pathType: Prefix
      prometheusSpec:
        retention: 5d
        storageSpec:
          volumeClaimTemplate:
            spec:
              resources:
                requests:
                  storage: 50Gi
