apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: prometheus-community
  namespace: monitoring
spec:
  interval: 10m0s
  url: https://prometheus-community.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  chart:
    spec:
      chart: kube-prometheus-stack
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
  interval: 10m0s
  values:
    grafana:
      enabled: false
    prometheus:
      ingress:
        enabled: disabled
        # annotations:
        #   cert-manager.io/cluster-issuer: letsencrypt
        # tls:
        #   - secretName: prometheus-tls
        #     hosts:
        #       - prometheus.internal.russparmer.dev
        # hosts:
        #   - prometheus.internal.russparmer.dev
        # path: /
        # pathType: Prefix
      # monitor:
      #   relabelings:
      #     - action: replace
      #       replacement: k3s
      #       targetLabel: cluster
      prometheusSpec:
        storageSpec:
          volumeClaimTemplate:
            spec:
              resources:
                requests:
                  storage: 10Gi
    # defaultRules:
    #   additionalRuleLabels:
    #     cluster: k3s
    # kube-state-metrics:
    #   prometheus:
    #     monitor:
    #       relabelings:
    #         - action: replace
    #           replacement: k3s
    #           targetLabel: cluster
    #         # - targetLabel: "instance"
    #         #   sourceLabels:
    #         #     - "__meta_kubernetes_pod_node_name"
    # prometheus-node-exporter:
    #   prometheus:
    #     monitor:
    #       relabelings:
    #         - action: replace
    #           replacement: k3s
    #           targetLabel: cluster
    #         # - targetLabel: "instance"
    #         #   sourceLabels:
    #         #     - "__meta_kubernetes_pod_node_name"
