apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: loki
  namespace: monitoring
spec:
  chart:
    spec:
      chart: loki
      sourceRef:
        kind: HelmRepository
        name: grafana
  interval: 10m0s
  values:
    loki:
      auth_enabled: false
      storage:
        type: s3
        bucketNames:
          chunks: loki-chunks
          ruler: loki-ruler
          admin: loki-admin
        s3:
          s3ForcePathStyle: true
      limits_config:
        split_queries_by_interval: 1h
      query_scheduler:
        max_outstanding_requests_per_tenant: 2048
      querier:
        max_concurrent: 20
    monitoring:
      dashboards:
        enabled: false
      lokiCanary:
        enabled: false
    test:
      enabled: false
    write:
      replicas: 3
      affinity: |
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    {{- include "loki.writeSelectorLabels" . | nindent 12 }}
                topologyKey: kubernetes.io/hostname
    read:
      replicas: 3
      affinity: |
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    {{- include "loki.readSelectorLabels" . | nindent 12 }}
                topologyKey: kubernetes.io/hostname
    backend:
      replicas: 3
      affinity: |
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    {{- include "loki.backendSelectorLabels" . | nindent 12 }}
                topologyKey: kubernetes.io/hostname
  valuesFrom:
    - targetPath: loki.storage.s3.region
      kind: Secret
      name: minio-access-creds
      valuesKey: AWS_REGION
    - targetPath: loki.storage.s3.endpoint
      kind: Secret
      name: minio-access-creds
      valuesKey: AWS_ENDPOINTS
    - targetPath: loki.storage.s3.accessKeyId
      kind: Secret
      name: minio-access-creds
      valuesKey: AWS_ACCESS_KEY_ID
    - targetPath: loki.storage.s3.secretAccessKey
      kind: Secret
      name: minio-access-creds
      valuesKey: AWS_SECRET_ACCESS_KEY
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: promtail
  namespace: monitoring
spec:
  chart:
    spec:
      chart: promtail
      sourceRef:
        kind: HelmRepository
        name: grafana
  interval: 10m0s
  values:
    initContainer:
      - name: init
        image: docker.io/busybox:1.33
        imagePullPolicy: IfNotPresent
        command:
          - sh
          - -c
          - sysctl -w fs.inotify.max_user_instances=512
        securityContext:
          privileged: true
