apiVersion: v1
kind: PersistentVolume
metadata:
  name: plex-media
  namespace: plex
spec:
  storageClassName: ""
  capacity:
    storage: 1000Gi
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /volume1/Media
    server: parmernas.local
    readOnly: true
