apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-config-pvc
  namespace: jellyfin
  labels:
    app: jellyfin
spec:
  storageClassName: longhorn
  volumeName: pvc-9172ccd2-d15e-43e7-9e55-262962962b3a
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-media-pvc
  namespace: jellyfin
  labels:
    app: jellyfin
spec:
  volumeName: jellyfin-media
  storageClassName: ""
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 1000Gi
