apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-data
  namespace: mongo
  labels:
    app: mongo
spec:
  storageClassName: parmernas-nfs
  accessModes:
    - ReadWriteOnce 
  resources:
    requests:
      storage: 1Gi