apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets
  namespace: mongo
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mongo-creds
  namespace: mongo
spec:
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  refreshInterval: 1h
  target:
    name: mongo-creds
  dataFrom:
    - extract:
        key: mongo-creds
