apiVersion: v1
kind: Service
metadata:
  name: mongo-svc
  namespace: mongo
  labels:
    app: mongo
spec:
  selector:
    app: mongo
  type: LoadBalancer
  loadBalancerIP: 192.168.2.204
  ports:
  - name: db
    port: 27017
    targetPort: db
