apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: cilium
  namespace: kube-system
spec:
  interval: 10m0s
  url: https://helm.cilium.io
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cilium
  namespace: kube-system
spec:
  chart:
    spec:
      chart: cilium
      sourceRef:
        kind: HelmRepository
        name: cilium
  interval: 10m0s
  values:
    rollOutCiliumPods: true
    annotateK8sNode: true
    kubeProxyReplacement: true
    k8sServiceHost: 192.168.2.20
    k8sServicePort: 6443
    kubeConfigPath: /etc/rancher/k3s/k3s.yaml
    kubeProxyReplacementHealthzBindAddr: 0.0.0.0:10256
    operator:
      replicas: 1
      rollOutPods: true
    ipam:
      operator:
        clusterPoolIPv4PodCIDRList: 10.42.0.0/16
    loadBalancer:
      algorithm: "maglev"
    securityContext:
      privileged: true
