apiVersion: cilium.io/v2alpha1
kind: CiliumLoadBalancerIPPool
metadata:
  name: pool
  namespace: kube-system
spec:
  blocks:
  - start: '192.168.2.251'
    stop: '192.168.2.254'
---
apiVersion: cilium.io/v2alpha1
kind: CiliumL2AnnouncementPolicy
metadata:
  name: default
  namespace: kube-system
spec:
  loadBalancerIPs: true
