apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-media
  labels:
    app: jellyfin
spec:
  storageClassName: ""
  capacity:
    storage: 1000Gi
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /volume1/Media
    server: 192.168.1.200
    readOnly: true
