apiVersion: v1
kind: Service
metadata:
  name: jellyfin-svc-tcp
  namespace: jellyfin
  labels:
    app: jellyfin
  annotations:
    metallb.universe.tf/allow-shared-ip: jellyfin
spec:
  selector:
    app: jellyfin
  type: LoadBalancer
  loadBalancerIP: 192.168.2.202
  sessionAffinity: ClientIP
  ports:
  - name: web
    port: 8096
    targetPort: web
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: jellyfin-svc-udp
  namespace: jellyfin
  labels:
    app: jellyfin
  annotations:
    metallb.universe.tf/allow-shared-ip: jellyfin
spec:
  selector:
    app: jellyfin
  type: LoadBalancer
  loadBalancerIP: 192.168.2.202
  sessionAffinity: ClientIP
  ports:
  - name: dlna-udp
    port: 1900
    targetPort: dlna-udp
    protocol: UDP
  - name: discovery-udp
    port: 7359
    targetPort: discovery-udp
    protocol: UDP
