apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: default-tls
  namespace: ingress-nginx
spec:
  secretName: default-tls
  dnsNames:
  - russparmer.dev
  - "*.russparmer.dev"
  # - "*.internal.russparmer.dev"
  issuerRef:
    name: letsencrypt
    # We can reference ClusterIssuers by changing the kind here.
    # The default value is Issuer (i.e. a locally namespaced Issuer)
    kind: ClusterIssuer
    group: cert-manager.io
