kubeProxyReplacement: true
kubeConfigPath: /etc/rancher/k3s/k3s.yaml
kubeProxyReplacementHealthzBindAddr: 0.0.0.0:10256
operator:
  replicas: 2
  rollOutPods: true
ipam:
  operator:
    clusterPoolIPv4PodCIDRList: 10.42.0.0/16
loadBalancer:
  algorithm: "maglev"
securityContext:
  privileged: true
