apiVersion: v1
kind: Namespace
metadata:
  name: minecraft
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets
  namespace: minecraft
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: curseforge-api-token
  namespace: minecraft
spec:
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  refreshInterval: 1h
  target:
    name: curseforge-api-token
  dataFrom:
    - extract:
        key: curseforge-api-token
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: itzg
  namespace: minecraft
spec:
  interval: 10m0s
  url: https://itzg.github.io/minecraft-server-charts/
