# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: minecraft-forge-mods
#   labels:
#     app: minecraft-forge
# spec:
#   storageClassName: ""
#   capacity:
#     storage: 1000Gi
#   accessModes:
#     - ReadWriteOnce
#   persistentVolumeReclaimPolicy: Retain
#   nfs:
#     path: /volume1/minecraft-mods
#     server: 192.168.1.200
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: minecraft-forge-mods
#   namespace: minecraft
#   labels:
#     app: minecraft-forge
# spec:
#   volumeName: minecraft-forge-mods
#   storageClassName: ""
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 1000Gi
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: minecraft-forge
  namespace: minecraft
spec:
  chart:
    spec:
      chart: minecraft
      sourceRef:
        kind: HelmRepository
        name: itzg
  interval: 10m0s
  values:
    image:
      tag: java17-graalvm
    persistence:
      dataDir:
        enabled: true
        Size: 10Gi
    resources:
      requests:
        memory: 12288Mi
        cpu: 2
    # extraEnv:
    # #   # USE_MODPACK_START_SCRIPT: "false"
      # CF_MODPACK_ZIP: /downloads/modpacks/New+Christmas+-+MC+1.20.1+-+6.0.1.zip
    # extraVolumes:
    #   - volumes:
    #       - name: mods
    #         persistentVolumeClaim:
    #           claimName: minecraft-forge-mods
    #     volumeMounts:
    #       - name: mods
    #         mountPath: /downloads
            # readOnly: true
    minecraftServer:
      eula: "TRUE"
      version: 1.20.1
      type: AUTO_CURSEFORGE
      gameMode: creative
      memory: 12288M
      forcegameMode: true
      overrideServerProperties: true
      motd: "Welcome to Parmer Forge!!"
      
      # service config
      serviceType: LoadBalancer
      loadBalancerIP: 192.168.2.202

      # allowed users
      whitelist: enderdragonbb,VelocityMoon_,potato_corgi_13

      # admins
      ops: enderdragonbb,VelocityMoon_,potato_corgi_13

      # cfServerMod: https://www.curseforge.com/api/v1/mods/476173/files/4972384/download
      autoCurseForge:
        apiKey:
          existingSecret: curseforge-api-token
          secretKey: token
        pageUrl: https://www.curseforge.com/minecraft/modpacks/all-the-mods-9/files/5003355
        # slug: all-the-mods-9
        # fileId: "4972384"
        parallelDownloads: 10
        excludeMods:
          - all-the-wizard-gear
          - towers-of-the-wild-modded
          - structory

    # livenessProbe:
    #   command:
    #     - mc-health
    #   initialDelaySeconds: 0
    #   periodSeconds: 5
    #   failureThreshold: 3
    #   successThreshold: 1
    #   timeoutSeconds: 1
    #   terminationGracePeriodSeconds: 30
    # readinessProbe:
    #   command:
    #     - mc-health
    #   initialDelaySeconds: 0
    #   periodSeconds: 5
    #   failureThreshold: 3
    #   successThreshold: 1
    #   timeoutSeconds: 1
    startupProbe:
      command:
        - mc-health
      enabled: true
      failureThreshold: 30
      periodSeconds: 10
    