---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cilium
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./k3s/cilium
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: metallb
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./k3s/metallb
  dependsOn:
    - name: cilium
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: nfs
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./k3s/nfs
  dependsOn:
    - name: cilium
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: longhorn
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./k3s/longhorn
  dependsOn:
    - name: cilium
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: system-upgrade
  namespace: flux-system
spec:
  interval: 24h
  path: ./k3s/system-upgrade
  dependsOn:
    - name: cilium
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-secrets
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./k3s/external-secrets
  dependsOn:
    - name: cilium
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: amd-gpu
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./k3s/amd-gpu
  dependsOn:
    - name: cilium
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: minecraft
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./k3s/minecraft
  dependsOn:
    - name: metallb
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: jellyfin
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./k3s/jellyfin
  dependsOn:
    - name: metallb
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: dynamic-ip
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./k3s/dynamic-ip
  dependsOn:
    - name: external-secrets
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./k3s/cert-manager
  dependsOn:
    - name: external-secrets
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-notifications
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./k3s/flux-notifications
  dependsOn:
    - name: external-secrets
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: nginx
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./k3s/nginx
  dependsOn:
    - name: metallb
    - name: cert-manager
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
