apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets
  namespace: splunk
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: splunk
  namespace: splunk
spec:
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  refreshInterval: 1h
  target:
    name: splunk
  dataFrom:
    - extract:
        key: splunk
