apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: splunk-etc
  namespace: splunk
  labels:
    app: splunk
spec:
  storageClassName: parmernas-nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: splunk-var
  namespace: splunk
  labels:
    app: splunk
spec:
  storageClassName: parmernas-nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
