apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: nfs-subdir-external-provisioner
  namespace: kube-system
spec:
  interval: 10m0s
  url: https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: nfs-provisioner
  namespace: kube-system
spec:
  chart:
    spec:
      chart: nfs-subdir-external-provisioner
      sourceRef:
        kind: HelmRepository
        name: nfs-subdir-external-provisioner
  interval: 10m0s
  values:
    nfs:
      server: 192.168.1.200
      path: /volume1/k3s
    storageClass:
      name: parmernas-nfs
      provisionerName: parmernas/nfs
      archiveOnDelete: false
