apiVersion: v1
kind: Namespace
metadata:
  name: vault
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: hashicorp
  namespace: vault
spec:
  interval: 10m0s
  url: https://helm.releases.hashicorp.com
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vault
  namespace: vault
spec:
  chart:
    spec:
      chart: vault
      sourceRef:
        kind: HelmRepository
        name: hashicorp
  interval: 10m0s
  values:
    injector:
      enabled: false
    server:
      dataStorage:
        enabled: true
        size: 10Gi
      ingress:
        enabled: true
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt
        tls:
          - secretName: vault-tls
            hosts:
              - vault.internal.russparmer.dev
        hosts:
          - host: vault.internal.russparmer.dev
      postStart:
        - /bin/sh
        - /vault/userconfig/unseal.sh
      volumes:
        - name: vault-unseal
          configMap:
            name: vault-unseal
      volumeMounts:
        - name: vault-unseal
          mountPath: /vault/userconfig
          readOnly: true
